[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tag_the_chart_program = "75SUaVzpGhU8R1TGJeS4zK4vBWWr1YtAQtWbNwY2C2or"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 30000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

# Clone Raydium CLMM program
[[test.validator.clone]]
address = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

# Clone pool
[[test.validator.clone]]
address = "6A1PJ4HnmhX7KHHrBS9FvSLQoU7hzauB8hvFQtvrfGUi"

# Clone AMM Config
[[test.validator.clone]]
address = "E64NGkDLLCdQ2yFNPcavaKptrEgmiQaNykUuLC1Qgwyp"

# Clone Token Mint B (Token A is native SOL, already exists)
[[test.validator.clone]]
address = "2FkQTGLFjyh3VV7d87PzYdj7SfnFAr5s9SdmwBA6ewfN"

# Clone Token Vaults
[[test.validator.clone]]
address = "E2iFJ6FGgg1RrcDpYroD7SWsymxEwVE6cVnJTLymw4AH"

[[test.validator.clone]]
address = "9PuJ93VoZr5n8SASp2XPLWy6WWWDzKAw53nLU1CEVEvs"

# Clone Observation State
[[test.validator.clone]]
address = "5PweRL9wvdAh392QWQ8ai6KRjJsGvVoCPFcdV6TXXeEW"

# Clone Tick Arrays
[[test.validator.clone]]
address = "GpPrWJWrC4nzqfAowphG1w2M5mssRDfgm8C935FJ1WPc"

[[test.validator.clone]]
address = "3YXKzxR94DqWVt7NMeCEFdEPXAEaZgJ4Mo2mcdDrLKiZ"

# Clone token holder wallet (owner keypair)
[[test.validator.clone]]
address = "AANe5UL6nsobFf9SBdt9xtY6DTFiA6eutqZ1fMRqJ8He"

# Clone token holder ATA
[[test.validator.clone]]
address = "7XA77DBfhYuzeLc9Qx2BM8zxxfsStu9NfRN7n1HRz71W"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

